# Data Structure

## List

In [1]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [2]:
#list hanya bisa ditambahkan dengan list
my_list + 4

TypeError: can only concatenate list (not "int") to list

In [3]:
my_list + [4,5]

[1, 2, 3, 4, 5]

In [4]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [5]:
my_list.append(3)
print(my_list)

[1, 2, 3, 3]


In [6]:
my_list.append([4,5])
print(my_list)

[1, 2, 3, 3, [4, 5]]


In [7]:
my_list = [1,2,3,4]

In [8]:
#hanya bisa menambah 1 
my_list.append([4,5])
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [9]:
mylist = [1,2,3]
mylist.extend([4,5,6])
print(mylist)

[1, 2, 3, 4, 5, 6]


In [10]:
mylist.remove(4)

In [11]:
print(mylist)

[1, 2, 3, 5, 6]


In [12]:
my_list

[1, 2, 3, 4, [4, 5]]

In [13]:
my_list.remove([4,5])

In [14]:
print(my_list)

[1, 2, 3, 4]


## Dictionary

In [15]:
student = {}
student = {'name':'Raka', 'age':18}

In [16]:
employee = {'cto':{'name':'raka', 'age': 18}}

In [17]:
student = dict(name='Billy', age=38)

In [18]:
print(student['name'])

Billy


In [19]:
print(student['age'])

38


In [20]:
print(student)

{'name': 'Billy', 'age': 38}


In [21]:
del student['age']

In [22]:
print(student)

{'name': 'Billy'}


In [23]:
student = {'name':'Raka', 'age':17}
print(student.keys())
print(student.values())

dict_keys(['name', 'age'])
dict_values(['Raka', 17])


## Tuples

In [24]:
#Tuples tidak bisa diubah, immutables
#dibuat dengan notasi ()

In [25]:
people = ('Raka', ('kode', 'random'))
print(people)

('Raka', ('kode', 'random'))


In [26]:
print(people[0])

Raka


In [27]:
print(people[1])

('kode', 'random')


In [28]:
print(people[1][0])
print(people[1][1])

kode
random


In [29]:
#slicing tuple
numbers = (1,2,3,4)
new_numbers = numbers[0], numbers[1:3]
print(new_numbers)

(1, (2, 3))


In [30]:
print(numbers)

(1, 2, 3, 4)


In [31]:
#sorting, harus konversi dulu dari tuple ke list
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body' )
email_attr_list = list(email_attr)

In [32]:
email_attr_list.sort()

In [33]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


## Files

In [34]:
#open('*.txt', a)
myfile = open('text.txt', 'w')

In [35]:
myfile.write('halo text file!\n')

16

In [36]:
myfile.write('selamat tinggal text file!\n')

27

In [37]:
myfile.close()

In [38]:
myfile = open('text.txt')

In [39]:
myfile.readline()

'halo text file!\n'

In [40]:
myfile.readline()

'selamat tinggal text file!\n'

In [41]:
#membaca seluruh isi
open('text.txt').read()

'halo text file!\nselamat tinggal text file!\n'

In [42]:
print(open('text.txt').read())

halo text file!
selamat tinggal text file!



In [89]:
x, y, z = 43, 44, 45

In [90]:
message= 'Spam'

In [91]:
data = {'a': 1, 'b':2}
list = [1,2,3]

In [92]:
file = open('text.txt', 'w')

In [93]:
file.write(message + '\n')

5

In [94]:
file.write('%s,%s,%s\n' % (x,y,z))

9

In [97]:
#konversi list ke string
file.write(str(list) + '$' + str(data) + '\n')

27

In [98]:
#untuk melihat hasil
file.close()

## Loops & Iterators

### while

In [1]:
#while test :
    #statements

In [ ]:
# infinite loop (looping terus menerus)
while True:
    print('PrintCtrl-C to stop me!')

In [4]:
message = "spam"
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [5]:
a = 0
b = 13
while a < b :
    print(a, end= ' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [6]:
#break utk keluar dari loop
#syntaks berikut :
while test:
    statements
    if test: break
        if test: continue
else:
    statements
        


IndentationError: unexpected indent (2242564584.py, line 6)

In [8]:
#yg paling umum adalah break
while True: 
    name = input('Enter name: ')
    if name == 'stop': break
    age = input('Enter age: ')
    print('Hello', name, '=>', int(age) ** 2)

Enter name: raka
Enter age: 12
Hello raka => 144
Enter name: dini
Enter age: 21
Hello dini => 441
Enter name: stop


### For loop

In [9]:
for word in ['raka', 'billy', 'kode']:
    print(word, end='\n')

raka
billy
kode


In [10]:
sum = 0
for i in [1,2,3,4]:
    sum = sum + i
sum

10

In [11]:
prod = 1
for item in [1,2,3,4]: prod *= item

In [12]:
prod

24

In [13]:
text = 'foxy fox'
words = ('is', 'great', 'animal')
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [14]:
for word in words: print(word, end='...')

is...great...animal...

In [17]:
coor = [(1,2), (3,4), (5,6)]
for(x, y) in coor: print(x,y)

1 2
3 4
5 6


## Branching in python

### if statement

In [ ]:
#syntaks:
if kondisi1:
    blok kode1
elif kondisi2:
    blok kode2
else: 
    blok kode3

In [19]:
if 1:
    print ('true')

true


In [20]:
if not 1:
    print('true')
else:
    print('false')

false


In [24]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 17
Time to get started!


In [27]:
user_age = input('Enter your age: ')
age = int(user_age) * 365
if age >= 9490:
    print('You are a Jedi Master now. Go learn from Master Yoda!!')
elif age >= 8395 and age < 9490 :
    print('Becoming Jedi Knight')
else:
    print('You are a young Padawan')

Enter your age: 17
You are a young Padawan


## Functions & Packages

### Functions

In [2]:
def add(a, b):
    return a + b

In [3]:
add(5,4)

9

In [4]:
add_things = add(10, 4)

In [5]:
print(add_things)

14


In [6]:
def add_and_print(a, b):
    print(a + b)

In [7]:
add_and_print(1,3)

4


In [8]:
x = add_and_print(5,3)

8


In [9]:
print(x)

None


In [10]:
def intersection(first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [11]:
word1 = 'spam'
word2 = 'scam'
char_of_intersect = intersection(word1, word2)
print(char_of_intersect)

['s', 'a', 'm']


### Modules & Built in Function

In [12]:
print(abs(-123))

123


In [13]:
print(abs(123))

123


In [16]:
#apakah si number adalah list
numbers = [1,2,3]
print(isinstance(numbers, list))

True


In [15]:
print(isinstance(numbers, dict))

False


In [17]:
number = 22

In [19]:
print(isinstance(number, list))

False


In [20]:
print(isinstance(numbers, int))

False


In [21]:
numbers = [1,2,3,4,5,6]
print(max(numbers))

6


In [22]:
print(min(numbers))

1


In [24]:
alphas = ['a', 'b', 'z']
print(max(alphas))
print(min(alphas))

z
a


### built in metode

In [25]:
languages = ['py', 'js', 'go', 'c']
print(languages.index('go'))

2


In [26]:
languages.sort()
print(languages)

['c', 'go', 'js', 'py']


In [27]:
name = 'raka'
print(name)

raka


In [28]:
name.replace('k', 'c')

'raca'

In [29]:
name.capitalize()

'Raka'

### Packages

In [34]:
import requests

In [35]:
r = requests.get('https://api.github.com/events')

In [36]:
print(r.status_code)

200


In [37]:
print(r.json())

[{'id': '31830657782', 'type': 'PullRequestEvent', 'actor': {'id': 8098421, 'login': 'radnov', 'display_login': 'radnov', 'gravatar_id': '', 'url': 'https://api.github.com/users/radnov', 'avatar_url': 'https://avatars.githubusercontent.com/u/8098421?'}, 'repo': {'id': 149104249, 'name': 'dhis2/metadata-package-development', 'url': 'https://api.github.com/repos/dhis2/metadata-package-development'}, 'payload': {'action': 'opened', 'number': 60, 'pull_request': {'url': 'https://api.github.com/repos/dhis2/metadata-package-development/pulls/60', 'id': 1515422147, 'node_id': 'PR_kwDOCOMmec5aU4HD', 'html_url': 'https://github.com/dhis2/metadata-package-development/pull/60', 'diff_url': 'https://github.com/dhis2/metadata-package-development/pull/60.diff', 'patch_url': 'https://github.com/dhis2/metadata-package-development/pull/60.patch', 'issue_url': 'https://api.github.com/repos/dhis2/metadata-package-development/issues/60', 'number': 60, 'state': 'open', 'locked': False, 'title': 'refactor: 

### Numpy

In [1]:
import numpy as np

In [2]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]

In [3]:
weight / height **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
np_height = np.array(height)
np_weight = np.array(weight)

In [6]:
bmi = np_weight/np_height ** 2

In [7]:
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


In [8]:
mixed_array = np.array([1.0, 'is', True])

In [10]:
#keluarnya jadi string semua
print(mixed_array)

['1.0' 'is' 'True']


In [11]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [13]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [14]:
bmi > 24

array([False, False, False,  True, False])

In [15]:
bmi[bmi>24]

array([27.03214188])

#### statistik dasar

In [16]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)

In [17]:
height

array([1.68, 1.47, 1.75, ..., 1.33, 1.73, 1.56])

In [18]:
#mengecek banyak data
len(height)

5000

In [19]:
#random normal = menghasilkan angka acak dgn parameter yaitu rata2, standar deviasi dan
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [20]:
weight

array([59.08, 43.35, 35.12, ..., 81.72, 66.29, 29.4 ])

In [21]:
len(weight)

5000

In [22]:
np_city = np.column_stack((height, weight))

In [24]:
#rata-rata
np.mean(np_city[:,0])

1.7548879999999998

In [25]:
np.median(np_city[:,0])

1.75

In [26]:
np.std(np_city[:,0])

0.20110511543966253

### Numpy Array 2D

In [27]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])

In [28]:
type(height)

numpy.ndarray

In [29]:
np_2d = np.array([[1.75, 1.68, 1.8], 
                 [66.4, 49.22, 66.3]])

In [30]:
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [32]:
#berapa baris dan kolom
np_2d.shape

(2, 3)

In [33]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [34]:
np_2d[0][2]

1.8

In [37]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [38]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])