# Numpy Introduction

In [1]:
import numpy as np

## Array

In [2]:
# np.array()
# np.zeros()
# np.ones()
# np.empty()
# np.arange()

In [3]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# You can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
# or an array filled with is:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
# you can create an array with a range of elemts

print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [8]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

### Add, Remove, and Sort

In [9]:
# np.append()
# np.delete()
# np.sort()

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
#menambahkan elemen di last
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

In [15]:
# ndarray.ndim()
# ndarray.size()
# ndarray.shape()

In [16]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim

3

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

In [20]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

### Reshape

In [24]:
# np.reshape()

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
# numpy.reshape(a, newshape, order)

### Convert 1D to 2D

In [29]:
# np.newaxis
# np.expand_dims

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
# you can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [32]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [33]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
# you can use np.expand_dims to add an axist at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
# You can add an axist at index position 0 with:

c= np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [38]:
c

array([[1, 2, 3, 4, 5, 6]])

### Indexing and Slicing

In [40]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [41]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# you can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [43]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [44]:
# you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [45]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) &  (a < 11)] 

print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [46]:
# slicing indexing
# np.vstack()
# np.hstack()
# np.hsplit()
# .view()
# .copy()

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [48]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [52]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [53]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [54]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [55]:
# or stack them horizontally with hstack

In [56]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [57]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [58]:
# if you wantes to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
# you can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
# using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

In [62]:
a = np.array([1, 2, 3, 4])

# add all of the elements in the array
a.sum()

10

In [63]:
b = np.array([[1, 1,], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [64]:
# you can sum the rows 

b.sum(axis=0)

array([3, 3])

In [65]:
# you can sum the columns

b.sum(axis=1)

array([2, 4])

In [66]:
data = np.array([1, 2])
data

array([1, 2])

In [67]:
ones = np.ones(2)
ones

array([1., 1.])

In [68]:
data + ones

array([2., 3.])

In [69]:
data * data

array([1, 4])

In [71]:
data / data

array([1., 1.])

### Broadcasting

In [72]:
data * 2

array([2, 4])

### More array operations

In [73]:
# data.max()
# data.min()
# data.sum()

In [74]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [75]:
A.sum()

4.8595784

In [76]:
A.min()

0.05093587

In [77]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [78]:
A.max()

0.82485143

In [79]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [80]:
A.std()

0.21392120766089617

## Matrices

## Creating Matrices

In [81]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.60408138, 0.88182532],
       [0.23841078, 0.62612385],
       [0.82538554, 0.41763258]])

In [82]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.61450498 0.23784475]
 [0.7445754  0.70968033]
 [0.15373809 0.91162902]]


### Mtarix Arithmetic

In [83]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [84]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [85]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [86]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [87]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [88]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [89]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix indexing

In [91]:
data = np.array([[1,2], [3,4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix aggregation

In [92]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [96]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [97]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [98]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [99]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [100]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [105]:
ndarr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [106]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [107]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [108]:
print(np.random.random((4,3,2)))

[[[0.75784258 0.85802326]
  [0.17482327 0.00328967]
  [0.37735879 0.58647581]]

 [[0.78457334 0.63748747]
  [0.67656588 0.38563887]
  [0.97866526 0.74970679]]

 [[0.24720535 0.25574087]
  [0.0558921  0.63625113]
  [0.94367837 0.37013065]]

 [[0.70998024 0.47230811]
  [0.8411316  0.319578  ]
  [0.4909428  0.95686826]]]


### Flatten N-Dimensional Array

In [109]:
# .flatten()
# .ravel()

In [111]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [113]:
# ypu can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [114]:
# rumus mean square error

error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined