# NumPy

In [1]:
import numpy as np

In [4]:
#array adalah struktur data central numpy
l = [[1,2,3],[2,5,6],[7,8,9]]
type(l)

list

In [6]:
a = np.array([[1,2,3],[2,5,6],[7,8,9]])
type(a)

numpy.ndarray

In [10]:
a = np.array([[1,2,3],[2,5,6],[7,8,9]])
b = [[1,2,3],[2,5,6],[7,8,9]]
display(a[0])
print(a[0])
b[0]

array([1, 2, 3])

[1 2 3]


[1, 2, 3]

In [11]:
display(type(a[0]))

numpy.ndarray

In [12]:
print([1 2 3])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3773061721.py, line 1)

In [13]:
print([123])

[123]


In [14]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [27]:
#np.zeros(6)

In [25]:
#np.ones(6)

In [30]:
#np.empty(6, order='F')
np.arange(4)

array([0, 1, 2, 3])

In [32]:
np.arange(5,20,2) 
#start stop step

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
cth = np.arange(5,10,2)
cth

array([5, 7, 9])

In [41]:
np.append(cth, [1,2,3]) #minimal 2 array pd append

#deleting element of array by index
np.delete(cth, 1) 

#cth = np.append(cth, [1,2,10])
np.sort(cth)

array([5, 7, 9])

In [40]:
ndarray.ndim()

ndarray.size()

ndarray.shape()

array([5, 7, 9])

In [42]:
array_example = np.array([
    [ 
        [0,1,2,3],
        [4,5,6,7]],
     [ 
        [0,1,2,3],
        [4,5,6,7]],
    [ 
        [0,1,2,3],
        [4,5,6,7]]
])
print (array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [44]:
#show array dimension
print(array_example.ndim)

#show array total element
print(array_example.size)

#show array total element
print(array_example.shape)

3
24
(3, 2, 4)


In [46]:
array_example2 = np.array([
    [ 
        [0,1,2,3],
        [4,5,6,7]],
     [ 
        [0,1,2,3],
        [4,5,6,7]]
])
array_example2.shape

(2, 2, 4)

In [50]:
array_example3 = np.array([
    [ 
        [0,1,2,3],
        [4,5,6,7]],
])
array_example3.shape
array_example3.ndim
array_example3.size

8

In [63]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [64]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
b.ndim

2

In [60]:
# ndim adalah number of dimension
a.ndim 

1

## convert 1d to 2d

In [66]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
display(a)
a2 = a[np.newaxis]
display(a2)
a3 = a2[np.newaxis]
display(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [75]:
row_vector = a[:, np.newaxis]
row_vector

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [77]:
row_vector = a[np.newaxis, :]
row_vector

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [78]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
a = np.arange(5)
display (a)
display (a.shape)
b = np.expand_dims(a, axis=1)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0],
       [1],
       [2],
       [3],
       [4]])

(5, 1)

In [83]:
b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([[0, 1, 2, 3, 4]])

(1, 5)

In [85]:
print(a)
print(a[2])
print(a[:3])
print(a[::-1])
print(a[-2:])

[0 1 2 3 4]
2
[0 1 2]
[4 3 2 1 0]
[3 4]


In [89]:
array_example = np.array([
    [ 
        [0,1,2,3],
        [4,5,6,7]]
])
print (array_example)

[[[0 1 2 3]
  [4 5 6 7]]]


In [90]:
array_example[array_example >= 5]

array([5, 6, 7])

In [92]:
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [93]:
array_example[array_example%2 == 0]

array([0, 2, 4, 6])

In [95]:
array_example[array_example%2 == 0] & (array_example > 3)
array_example[array_example%2 == 0] | (array_example > 3) 

array([[[0, 2, 4, 6],
        [1, 3, 5, 7]]], dtype=int32)

## Creating array from existing data

In [98]:
a = np.arange(1,11)
b = a[3:8]
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
b

array([4, 5, 6, 7, 8])

In [103]:
a1 = np.array(
    [ 
        [0,1,],
        [4,5,]
])

a2 = np.array(
    [ 
        [2,3,],
        [6,7,]
])
a2

array([[2, 3],
       [6, 7]])

In [104]:
np.vstack((a1,a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [105]:
np.hstack((a1,a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [110]:
np.hsplit(a4,2)

[array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]])]

In [111]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
np.vstack((b,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
b = a.copy()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
## array dan copy biasanya kalo kita mau bereksperimen tanpa ngubah array aslinya

## basic array operation

In [121]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)

[0 1 2]
[4 5 6]


In [123]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [126]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [127]:
a3.sum()

120

In [129]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
c.sum(axis = 0)

array([15, 18, 21, 24])

In [131]:
# axis 0 adalah kolom, axis 1 adalah baris
print(c.sum(axis = 0))
print(c.sum(axis = 1))

[15 18 21 24]
[10 26 42]


## Broadcasting

In [132]:
a

array([0, 1, 2])

In [134]:
print(a)
a * 1.6

[0 1 2]


array([0. , 1.6, 3.2])

In [135]:
#karena beda tipe
z = np.array([1,2,'z'])
z * 15

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [136]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
print(c.min())
print(c.max())
print(c.sum())
print(c.std())
print(c.min(axis = 1))
print(c.max(axis = 1))
print(c.sum(axis = 1))

1
12
78
3.452052529534663
[1 5 9]
[ 4  8 12]
[10 26 42]


In [139]:
print(c.min(axis = 1))

[1 5 9]


## Matriks

In [148]:
z = np.zeros((6,2))
o = np.ones((6,2))
r = np.random.random((6,2))
print(z)
print(o)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.60099992 0.54378132]
 [0.34015317 0.74848305]
 [0.65182079 0.23244955]
 [0.28473125 0.59229992]
 [0.78466947 0.08258864]
 [0.35798838 0.93225036]]


### Matriks Aritmatika

In [149]:
r + o

array([[1.60099992, 1.54378132],
       [1.34015317, 1.74848305],
       [1.65182079, 1.23244955],
       [1.28473125, 1.59229992],
       [1.78466947, 1.08258864],
       [1.35798838, 1.93225036]])

### Dot Product

In [150]:
a1

array([[0, 1],
       [4, 5]])

In [151]:
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [162]:
a1 = np.array([[0,1],[4,5],[7,8]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[0 1 2]
 [4 5 6]]


In [163]:
np.dot(a1,a2)

array([[ 4,  5,  6],
       [20, 29, 38],
       [32, 47, 62]])

### Matrix Indexing

In [170]:
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


### Transpos & Reshaping

In [171]:
# dengan T
display(a1)
print(a1.shape)
print(a1.T)
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [172]:
a = np.arange(6)

In [173]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [174]:
a2.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [175]:
a2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [176]:
a2.reshape(3,-1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [177]:
a2.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

### Flatten N-Dimensioal Array

In [178]:
a3 = a2.reshape(-1,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [181]:
a4 = a3.flatten()
a4

array([0, 1, 2, 3, 4, 5])

In [183]:
np.delete(a4,1)

array([0, 2, 3, 4, 5])

In [184]:
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [188]:
a4 = a3.ravel()
a4

array([0, 1, 2, 3, 4, 5])

### working with math formulas